@hostname = 192.168.1.135
@port = 3000
@url = products

###

GET http://{{hostname}}:{{port}}/{{url}}

###

GET http://{{hostname}}:{{port}}/{{url}}/1

###


POST http://{{hostname}}:{{port}}/{{url}}
Content-Type: application/json

{
    "name":"Frying Pan",
    "sku": "FPA1",
    "description": "This is a frying pan",  
    "price": 25000,
    "currency": "DKK",
    "quantity": 5
}

###