@hostname = 192.168.1.135
@port = 3000
@url = products

###

GET http://{{hostname}}:{{port}}/{{url}}

###

GET http://{{hostname}}:{{port}}/{{url}}/14

###


POST http://{{hostname}}:{{port}}/{{url}}
Content-Type: application/json

{
    "name":"Xbox Series X",
    "sku": "XBX",
    "description": "This is an xbox series X console",
    "category":"electronics",
    "price": 500000,
    "currency": "DKK",
    "quantity": 1
}

###

PATCH  http://{{hostname}}:{{port}}/{{url}}
Content-Type: application/json

{
 "name":"Playstation 5",
 "price": 550000,
 "currency":"DKK"

}

###

POST http://localhost:3000/images/upload
Content-Type: multipart/form-data; boundary=TestData

--TestData
Content-Disposition: form-data; name="image"; filename="72943496-7458-4234-9cb0-e4aeb7c8db41.jpeg"
Content-Type: text/plain

< .72943496-7458-4234-9cb0-e4aeb7c8db41.jpeg
--TestData--

